commands:
  money:
    description: "AAA"
    name: "money"
    aliases: []
    sub:
      pay:
        description: "AAA"
        name: "money"
        aliases: []
      set:
        description: "AAA"
        name: "money"
        aliases: []
      remove:
        description: "AAA"
        name: "money"
        aliases: []
      give:
        description: "AAA"
        name: "money"
        aliases: []
      see:
        description: "AAA"
        name: "money"
        aliases: []
  kit:
    description: "AAA"
    name: "kit"
    aliases: []
  shop:
    description: "AAA"
    name: "shop"
    aliases: []
  spawn:
    description: "AAA"
    name: "spawn"
    aliases: []
  arene:
    description: "AAA"
    name: "arene"
    aliases: []
  tuto:
    description: "AAA"
    name: "tuto"
    aliases: []
  farmzone:
    description: "AAA"
    name: "farmzone"
    aliases: []
  purif:
    description: "AAA"
    name: "purification"
    aliases: []
  clearlag:
    description: "AAA"
    name: "clearlag"
    aliases: []
  giveall:
    description: "AAA"
    name: "giveall"
    aliases: []
  id:
    description: "AAA"
    name: "id"
    aliases: []
  say:
    description: "AAA"
    name: "say"
    aliases: []
  size:
    description: "AAA"
    name: "size"
    aliases: []
  spy:
    description: "AAA"
    name: "spy"
    aliases: []
  tpall:
    description: "AAA"
    name: "tpall"
    aliases: []
  settings:
    description: "AAA"
    name: "settings"
    aliases: []
  discord:
    description: "AAA"
    name: "discord"
    aliases: []
  msg:
    description: "AAA"
    name: "message"
    aliases: ["tell", "msg"]
  nv:
    description: "AAA"
    name: "nightvision"
    aliases: []
  ping:
    description: "AAA"
    name: "ping"
    aliases: []
  reply:
    description: "AAA"
    name: "reply"
    aliases: ["r"]
  craft:
    description: "AAA"
    name: "craft"
    aliases: []
  ec:
    description: "AAA"
    name: "ec"
    aliases: []
  near:
    description: "AAA"
    name: "near"
    aliases: []
  rename:
    description: "AAA"
    name: "rename"
    aliases: []
  repair:
    description: "AAA"
    name: "repair"
    aliases: []
  minagenpc:
    description: "AAA"
    name: "minagenpc"
    aliases: []

database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: faction.sqlite
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: your_schema
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1