commands:
  money:
    description: "AAA"
    name: "money"
    aliases: []
    sub:
      pay:
        description: "AAA"
        name: "money"
        aliases: []
      set:
        description: "AAA"
        name: "money"
        aliases: [ ]
      remove:
        description: "AAA"
        name: "money"
        aliases: [ ]
      give:
        description: "AAA"
        name: "money"
        aliases: [ ]
      see:
        description: "AAA"
        name: "money"
        aliases: [ ]
  kit:
    description: "AAA"
    name: "kit"
    aliases: [ ]